### ISSUE TITLE
fix(figmage_package_generator): Typography not added to export

### ISSUE THREAD

**Issue by JesperBllnbm** [whynotmake-it/figmage#38] opened 2023-12-21 11:00 UTC
**Description**

The export for the typography.dart file is not added

```dart
/// Design Tokens generated from our Figma
library design_token_package;

export 'src/numbers.dart';
export 'src/paddings.dart';

export 'src/spacers.dart';


```

**Comment by timcreatedit** [comment] 2023-12-21 11:15
Taking a look 👀

**Comment by timcreatedit** [comment] 2023-12-21 11:39
@JesperBllnbm I've tried to write a failing test case in #41 but it seems to work just fine? Did it generate the dart file and just the export was missing in your case, or were both gone because then the error is somewhere else 😬

**Comment by JesperBllnbm** [comment] 2023-12-21 14:10
Just the export was missing, the file was there

**Comment by timcreatedit** [comment] 2023-12-21 14:13
With this config?:

```yaml
# ...
colors:
  generate: true
  from:
    - 'Wireframe Themes'
typography:
  generate: true
  from:
strings:
  generate: false
bools:
  generate: false
spacers:
  generate: false
paddings:
  generate: false
radii:
  generate: false
```

**Comment by timcreatedit** [comment] 2024-04-15 12:35
I will close this for now bc I can't find a way to reproduce it. Feel free to reopen if you have more info :)

**Closed by timcreatedit** 2024-04-15 12:35 UTC
Labels: bug
